export enum SharedListItemActionType {
    ADD_SHARED_ITEM_BEGIN = 'ADD_SHARED_ITEM_BEGIN',
    ADD_SHARED_ITEM_SUCCESS = 'ADD_SHARED_ITEM_SUCCESS',
    DELETE_SHARED_ITEM_BEGIN = 'DELETE_SHARED_ITEM_BEGIN',
    DELETE_SHARED_ITEM_SUCCESS = 'DELETE_SHARED_ITEM_SUCCESS',
    SHARE_SHARED_ITEM = 'SHARE_SHARED_ITEM'
}