export enum ModeratedListActionType {
    FETCH_MODERATED_LISTS_BEGIN = 'FETCH_MODERATED_LISTS_BEGIN',
    FETCH_MODERATED_LISTS_SUCCESS = 'FETCH_MODERATED_LISTS_SUCCESS',
    CLEAR_MODERATED_LISTS_STATE = 'CLEAR_MODERATED_LISTS_STATE'
}