export enum PrivateBookListActionType {
    SET_PRIVATE_LIST = 'SET_PRIVATE_LIST',
    UNSET_PRIVATE_LIST = 'UNSET_PRIVATE_LIST',
    ADD_ITEM = 'ADD_ITEM',
    REMOVE_ITEM = 'REMOVE_ITEM',
    UPDATE_ITEM = 'UPDATE_ITEM',
    SWITCH_ITEM_EDIT_MODE = 'SWITCH_ITEM_EDIT_MODE',
    SWITCH_LIST_EDIT_MODE = 'SWITCH_LIST_EDIT_MODE',
    UPDATE_LIST_NAME = 'UPDATE_LIST_NAME'
}