export enum PrivateListActionType {
    FETCH_PRIVATE_LIST_BEGIN = 'FETCH_PRIVATE_LIST_BEGIN',
    FETCH_PRIVATE_LIST_SUCCESS = 'FETCH_PRIVATE_LIST_SUCCESS',
    UPDATE_PRIVATE_LIST_BEGIN = 'UPDATE_PRIVATE_LIST_BEGIN',
    UPDATE_PRIVATE_LIST_SUCCESS = 'UPDATE_PRIVATE_LIST_SUCCESS',
    UNSET_PRIVATE_LIST = 'UNSET_PRIVATE_LIST',
    SWITCH_PRIVATE_LIST_MODE = 'SWITCH_PRIVATE_LIST_MODE',
    SHARE_PRIVATE_LIST = 'SHARE_PRIVATE_LIST'
}