export enum BookActionType {
    FIND_BOOKS_BEGIN = 'FIND_BOOKS_BEGIN',
    FIND_BOOKS_SUCCESS = 'FIND_BOOKS_SUCCESS',
    SHARE_BOOK_BEGIN = 'SHARE_BOOK_BEGIN',
    CLEAR_BOOK_STATE = 'CLEAR_BOOK_STATE'
}