export enum BookListActionType {
    SET_PRIVATE_LIST = 'SET_PRIVATE_LIST',
    UNSET_PRIVATE_LIST = 'UNSET_PRIVATE_LIST',
    ADD_ITEM = 'ADD_ITEM',
    REMOVE_ITEM = 'REMOVE_ITEM',
    UPDATE_ITEM = 'UPDATE_ITEM',
    SWITCH_EDIT_MODE = 'SWITCH_EDIT_MODE'
}