//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadingList.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change status from {0} to {1}.
        /// </summary>
        public static string CannotChangeStatusFromTo {
            get {
                return ResourceManager.GetString("CannotChangeStatusFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediator is not initialized.
        /// </summary>
        public static string MediatorNotInitialized {
            get {
                return ResourceManager.GetString("MediatorNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist.
        /// </summary>
        public static string ObjectNotExist {
            get {
                return ResourceManager.GetString("ObjectNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object with {0}.
        /// </summary>
        public static string ObjectNotExist_Default {
            get {
                return ResourceManager.GetString("ObjectNotExist_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private list for user with {0}.
        /// </summary>
        public static string ObjectNotExist_PrivateBookList {
            get {
                return ResourceManager.GetString("ObjectNotExist_PrivateBookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with {0}.
        /// </summary>
        public static string ObjectNotExist_PrivateBookListItem {
            get {
                return ResourceManager.GetString("ObjectNotExist_PrivateBookListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with {0}.
        /// </summary>
        public static string ObjectNotExist_User {
            get {
                return ResourceManager.GetString("ObjectNotExist_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wasn&apos;t found.
        /// </summary>
        public static string ObjectNotFound {
            get {
                return ResourceManager.GetString("ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} wasn&apos;t found.
        /// </summary>
        public static string ObjectNotFoundWithData {
            get {
                return ResourceManager.GetString("ObjectNotFoundWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email {0} already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered wrong password. Please try again.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
