export enum PrivateListItemActionType {
    ADD_PRIVATE_ITEM_BEGIN = 'ADD_PRIVATE_ITEM_BEGIN',
    ADD_PRIVATE_ITEM_SUCCESS = 'ADD_PRIVATE_ITEM_SUCCESS',
    UPDATE_PRIVATE_ITEM_BEGIN = 'UPDATE_PRIVATE_ITEM_BEGIN',
    DELETE_PRIVATE_ITEM_BEGIN = 'DELETE_PRIVATE_ITEM_BEGIN',
    DELETE_PRIVATE_ITEM_SUCCESS = 'DELETE_PRIVATE_ITEM_SUCCESS',
    UPDATE_PRIVATE_ITEM_SUCCESS = 'UPDATE_PRIVATE_ITEM_SUCCESS',
    SWITCH_PRIVATE_ITEM_MODE = 'SWITCH_PRIVATE_ITEM_MODE',
    SHARE_PRIVATE_ITEM = 'SHARE_PRIVATE_ITEM'
}